### ISSUE TITLE
Update MSG_HAND message to include configuration

### ISSUE THREAD

**Issue by dansantorojr** [kamladi/dicio#30]

**Comment by dansantorojr** [comment]
Network message definition for MSG_HAND updated to include a two byte payload for use in sending this configuration information.

**Comment by dansantorojr** [comment]
Hey guys, I reopened this issue because I can't find the code for it anywhere. Point me in the right direction?

**Comment by dansantorojr** [comment]
![screen shot 2016-04-03 at 11 20 31 am](https://cloud.githubusercontent.com/assets/15403971/14233150/3f29baf4-f98e-11e5-8f88-bf74d08c89b1.png)

Found it, but it's not in master

**Comment by kamladi** [comment]
Oh whoops, for got to merge it in

**Comment by dansantorojr** [comment]
It could get kinda messy now cause I made a lot of changes...added all those "g_". Let me know if there is anything I can do to help out.

**Comment by kamladi** [comment]
merged it with 1d0c1d60c6b4045e008af7709f4014713430175a
